version: '3'

services:
  topone:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - ./work:/home/jovyan/work
      - ./external:/home/jovyan/topone/external
      - ./topone:/home/jovyan/topone/topone
      - ./setup.py:/home/jovyan/topone/setup.py
      - ./environment.yml:/home/jovyan/topone/environment.yml
      - $HOME/.Xauthority:/root/.Xauthority
    network_mode: "host"
