version: '3'

services:
  topone:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
      - ./external:/home/jovyan/topone/external
      - ./topone:/home/jovyan/topone/topone
      - ./setup.py:/home/jovyan/topone/setup.py
      - ./environment.yml:/home/jovyan/topone/environment.yml
      - ./config_files/overrides.json /opt/conda/share/jupyter/lab/settings/overrides.json
      - ./config_files/pycodestyle /home/jovyan/.config/pycodestyle
      - ./config_files/mypy_config /home/jovyan/.config/mypy/config

